name: flutter_todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  after_layout: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  retrofit: ^3.3.1
  dio: ^4.0.6
  built_value: ^8.4.3
  json_annotation: ^4.8.0
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  built_value_generator: ^8.4.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

